{% set name = "msgraph-core" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/msgraph_core-{{ version }}.tar.gz
  sha256: 91c721b4c741d0e9a536e3c43e1cbd2254928b4d207e4f994e9cc7cb7a25bd74

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - setuptools
    - wheel
    - pip
    - h2
  run:
    - python
    - microsoft-kiota-abstractions
    - microsoft-kiota-authentication-azure
    - microsoft-kiota-http
    - httpx
    - h2

test:
  imports:
    - msgraph_core
  commands:
    - pip check
  requires:
    - pip
    - python

about:
  home: https://github.com/microsoftgraph/msgraph-sdk-python-core
  summary: Core abstractions for kiota generated libraries in Python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/microsoftgraph/msgraph-sdk-python-core
  doc_url: https://github.com/microsoftgraph/msgraph-sdk-python-core/blob/main/README.md

extra:
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/64252
    reason: Dependency for msgraph-sdk
  recipe-maintainers:
    - ianaobi
  recipe-maintainers:
    - xylar
